# Generated by Django 5.2.13 on 2026-04-08 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('gamou', 'Gamou'), ('ziar', 'Ziar'), ('reunion', 'Réunion'), ('formation', 'Formation'), ('autre', 'Autre')], max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('lance', 'Lancé'), ('cloture', 'Clôturé')], default='brouillon', max_length=20)),
                ('est_global', models.BooleanField(default=False, help_text='Si True, concerne toutes les cellules (ex: Gamou)')),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cellule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='accounts.cellule')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='LigneBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('recette', 'Recette'), ('depense', 'Dépense')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_budget', to='evenements.evenement')),
            ],
            options={
                'verbose_name': 'Ligne budget',
                'verbose_name_plural': 'Lignes budget',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('present', 'Présent'), ('absent', 'Absent')], default='inscrit', max_length=15)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='evenements.evenement')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participation',
                'unique_together': {('membre', 'evenement')},
            },
        ),
    ]
