# Generated by Django 5.2.13 on 2026-04-08 18:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('UGB', 'Cellule UGB (Mère)'), ('DAKAR', 'Cellule Dakar'), ('NORD', 'Cellule Nord'), ('DIASPORA', 'Cellule Diaspora')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cellule',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('statut_matrimonial', models.CharField(blank=True, choices=[('marie', 'Marié(e)'), ('celibataire', 'Célibataire')], max_length=15)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_cellule', 'Admin Cellule'), ('membre_actif', 'Membre Actif'), ('membre_alumni', 'Membre Alumni')], default='membre_actif', max_length=20)),
                ('date_adhesion', models.DateField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('ufr', models.CharField(blank=True, choices=[('SAT', 'Sciences Appliquées et Technologies'), ('SEG', 'Sciences Économiques et Gestion'), ('IPSL', 'IPSL'), ('2S', 'Santé'), ('2SATA', 'Agronomie'), ('SJP', 'Droit'), ('LSH', 'Langues et Sciences Humaines'), ('SEFS', "Sciences de l'Éducation"), ('STAPS', 'STAPS')], max_length=10)),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('niveau_etude', models.CharField(blank=True, max_length=20)),
                ('promo', models.CharField(blank=True, max_length=10)),
                ('est_diplome', models.BooleanField(default=False)),
                ('annee_diplome', models.CharField(blank=True, max_length=4)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('cellule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='accounts.cellule')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
