# Generated by Django 5.2.13 on 2026-04-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_officialisation',
            field=models.DateField(blank=True, help_text='Date à laquelle le sympathisant est devenu membre officiel', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_signature_engagement',
            field=models.DateField(blank=True, help_text="Date de signature de l'engagement de cotisation mensuelle", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='est_bureau',
            field=models.BooleanField(default=False, help_text='Est-il membre du bureau ?'),
        ),
        migrations.AddField(
            model_name='user',
            name='poste_bureau',
            field=models.CharField(blank=True, choices=[('president', 'Président'), ('vice_president', 'Vice-Président'), ('sg', 'Secrétaire Général'), ('pdte_finance', 'Pdte Commission Finance'), ('tresorier', 'Trésorier Général'), ('adjt_tresorier', 'Adjoint Trésorier'), ('com_organisation', 'Commission Organisation'), ('com_logistique', 'Commission Logistique'), ('com_scientifique', 'Commission Scientifique et Culturelle'), ('cellule_comm', 'Cellule Communication'), ('com_sages', 'Commission des Sages')], help_text='Poste occupé au bureau (si est_bureau=True)', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='type_membre',
            field=models.CharField(choices=[('officiel', 'Membre Officiel'), ('sympathisant', 'Sympathisant')], default='sympathisant', help_text='Officiel = carte membre + cotisation 1000 FCFA/mois obligatoire', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_cellule', 'Admin Cellule'), ('membre', 'Membre')], default='membre', max_length=20),
        ),
    ]
