# Generated by Django 5.2.13 on 2026-04-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_officialisation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellule',
            options={'ordering': ['nom'], 'verbose_name': 'Cellule'},
        ),
        migrations.AlterField(
            model_name='user',
            name='promo',
            field=models.CharField(blank=True, help_text='Format P + numéro (ex: P30)', max_length=10),
        ),
    ]
