# Generated by Django 5.2.13 on 2026-06-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_cellule_options_alter_user_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellule',
            name='montant_cotisation',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Montant de référence : 1000 (mensuel) ou 50000 (annuel)', max_digits=10),
        ),
        migrations.AddField(
            model_name='cellule',
            name='type_bareme',
            field=models.CharField(choices=[('mensuel', 'Mensuel (étudiants)'), ('annuel', 'Annuel (anciens)'), ('aucun', 'Aucun (en attente)')], default='mensuel', help_text='Mensuel = 1000/mois (UGB), Annuel = 50000/an (Dakar, Nord)', max_length=10),
        ),
    ]
