# Generated by Django 5.2.13 on 2026-04-09 13:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotisationMensuelleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_mensuel', models.DecimalField(decimal_places=2, default=Decimal('1000'), help_text='Montant mensuel obligatoire pour les membres officiels', max_digits=10)),
                ('jour_rappel', models.IntegerField(default=1, help_text='Jour du mois pour envoyer la notification de rappel (1-28)')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Config Cotisation Mensuelle',
            },
        ),
        migrations.AddField(
            model_name='cotisation',
            name='mois_concerne',
            field=models.DateField(blank=True, help_text='Pour les cotisations mensuelles : le mois concerné (ex: 2024-01-01 = Janvier 2024)', null=True),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='reduction_membres_officiels',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Réduction accordée aux membres officiels (en FCFA)', max_digits=10),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='type_cotisation',
            field=models.CharField(choices=[('mensuelle', 'Cotisation Mensuelle (1000 FCFA)'), ('evenement', 'Cotisation Événement'), ('exceptionnelle', 'Cotisation Exceptionnelle')], default='evenement', max_length=15),
        ),
        migrations.AddField(
            model_name='paiement',
            name='reduction_appliquee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Réduction appliquée au moment du paiement', max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='periodicite',
            field=models.CharField(choices=[('mensuelle', 'Mensuelle'), ('annuelle', 'Annuelle'), ('unique', 'Unique')], default='unique', max_length=15),
        ),
    ]
