# Generated by Django 5.2.13 on 2026-04-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisations', '0002_cotisationmensuelleconfig_cotisation_mois_concerne_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotisation',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Cotisation', 'verbose_name_plural': 'Cotisations'},
        ),
    ]
